# Timestamp
uint32 timestamp

# Battery Voltage and Current
float32 volt_b_left
float32 curr_b_left
float32 volt_b_right
float32 curr_b_right

# Motor Current
float32 curr_m_left
float32 curr_m_right

# IMU - Orientation
float32 roll
float32 pitch
float32 yaw

# IMU - Accelerometer
float32 acc_x
float32 acc_y
float32 acc_z

# IMU - rotation rates
float32 roll_rate
float32 pitch_rate
float32 yaw_rate

# Sonar
float32 sonar_mm

# Sinkage depth
float32 tof_mm

# Motor RPM
float32 rpm_left
float32 rpm_right

# Motor number of rotations
float32 nrot_left
float32 nrot_right
